spin_manifest_version = 2

[application]
authors = ["Malhar Vora <mvora@ddn.com>"]
description = "This is test app"
name = "myapp"
version = "0.1.0"

[[trigger.http]]
route = "/hello"
component = "myapp"

[component.myapp]
source = "app.wasm"
[component.myapp.build]
command = "componentize-py -w spin-http componentize app -o app.wasm"
watch = ["*.py", "requirements.txt"]
